src/objects/Care_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Treatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Care Team Members</relationshipLabel>
        <relationshipName>Care_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Care_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Care Team Member</label>
    <nameField>
        <label>Care Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Communication__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Care_Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Care Team Member</label>
        <referenceTo>Care_Team_Member__c</referenceTo>
        <relationshipLabel>Communications</relationshipLabel>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Communication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Communication</label>
        <referenceTo>Communication__c</referenceTo>
        <relationshipLabel>Child Communications</relationshipLabel>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Treatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Communications</relationshipLabel>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Communication</label>
    <nameField>
        <label>Communication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Treatment__c.object
<CustomObject>
    <description>What Treatment is the patient interested in.</description>
    <label>Treatment</label>
    <nameField>
        <displayFormat>TR{00000000}</displayFormat>
        <label>Treatment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MessagingUtil.cls
public with sharing class MessagingUtil {
	private static Map<String, Care_Team_Member__c> userToCareTeamMemberMap = null;
	public static void loadCareTeamMemberMap( ID[] treatmentIds ) {
		Care_Team_Member__c[] members = [SELECT id, Treatment__c, User__c FROM Care_Team_Member__c 
			where Treatment__c in :treatmentIds];
		userToCareTeamMemberMap = new Map<String, Care_Team_Member__c>();
		for (Care_Team_Member__c member : members) {
			userToCareTeamMemberMap.put(member.Treatment__c+'+'+member.User__c, member);
		}
	}
	public static Communication__c createPrivateMessage( ID treatmentId, Id fromUser, Id toUser, String message ) {
		Care_Team_Member__c fromMember = userToCareTeamMemberMap.get(treatmentId+'+'+fromUser);
		Care_Team_Member__c toMember = userToCareTeamMemberMap.get(treatmentId+'+'+toUser);
		if (fromMember==null || toMember==null) return null;
		return new Communication__c( 
			Treatment__c = treatmentId,
			From_User__c = fromMember.id,
			Care_Team_Member__c = toMember.id,
			Body__c = message
			);
	}
}