src/objects/Care_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Doctor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Information Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onsite Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Concierge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Treatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Care Team Members</relationshipLabel>
        <relationshipName>Care_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Care_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Care Team Member</label>
    <nameField>
        <label>Care Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Treatment__c.object
<CustomObject>
    <description>What Treatment is the patient interested in.</description>
    <label>Treatment</label>
    <nameField>
        <displayFormat>TR{00000000}</displayFormat>
        <label>Treatment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/careTeam_Controller.cls
public with sharing class careTeam_Controller {

	public class careTeamMemberWrapper {
		public Id parentTreatmentId {get;set;}
		public Id userId {get;set;}
		public String name {get;set;}
		public String role {get;set;}
		public String imageURL {get;set;}
		public FeedItem newMessage {get;set;}
		public Task newTask {get;set;}
		public Boolean showMessage {get;set;}
		public Boolean showTask {get;set;}

		public careTeamMemberWrapper(Care_Team_Member__c c){
			parentTreatmentId = c.Treatment__c;
			userId = c.User__c;
			name = c.User__r.Name;
			role = c.Role__c;
			if ( c.User__r.FullPhotoUrl != null ){
				imageUrl = c.User__r.FullPhotoUrl;
			}
			cancel();
		}

		public PageReference composeMessage(){
			showMessage = true;
			newMessage = new FeedItem();
			newMessage.ParentId = userId;
			return null;
		}

		public PageReference insertMessage(){
			insert newMessage;
			cancel();
			return null;
		}

		public PageReference composeTask(){
			newTask = new Task();
			newTask.OwnerId = userId;
			newTask.Subject = 'Treatment Task';
			newTask.Status = 'Not Started';
			newTask.WhatId = parentTreatmentId;
			showTask = true;
			return null;
		}

		public PageReference insertTask(){
			insert newTask;
			cancel();
			return null;
		}
	
		public PageReference cancel(){
			showMessage = false;
			showTask = false;
			return null;
		}

	}

	public Id treatmentId {get;set;}
	public List<careTeamMemberWrapper> careTeamMemberList {
		get {
			if ( careTeamMemberList == null || careTeamMemberList.size() == 0){
				careTeamMemberList = new List<careTeamMemberWrapper>();
				for ( Care_Team_Member__c c : [Select Id, Treatment__c, Role__c, User__c, User__r.FullPhotoUrl, User__r.Name from Care_Team_Member__c where Treatment__c = :treatmentId order by Name]){
					careTeamMemberList.add(new careTeamMemberWrapper(c));
				}
			}
			return careTeamMemberList;
		}
		set;
	}

	public Care_Team_Member__c newCareTeamMember {get;set;}
	public PageReference addCareTeamMember(){
		newCareTeamMember = new Care_Team_Member__c();
		newCareTeamMember.Treatment__c = treatmentId;
		return null;
	}

	public PageReference insertNewCareTeamMember(){
		if ( newCareTeamMember.User__c != null /* && newCareTeamMember.Role__c != null*/ ) {
			CareTeamUtil.addMembersToCareTeam( new List<Care_Team_Member__c>{newCareTeamMember});
		} else {
			
		}
		return null;
	}

	public careTeam_Controller(){

		
	}	

}