src/objects/Care_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Medical_Professional__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Medical Professional</label>
        <referenceTo>Medical_Professional__c</referenceTo>
        <relationshipLabel>Care Team Members</relationshipLabel>
        <relationshipName>Care_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Treatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Care Team Members</relationshipLabel>
        <relationshipName>Care_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Care_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Care Team Member</label>
    <nameField>
        <label>Care Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/External_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Treatment__c</fullName>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>External Contact</relationshipLabel>
        <relationshipName>External_Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>External Contact</label>
    <nameField>
        <label>External Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Contact</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Medical_Professional__c.object
<CustomObject>
    <label>Medical Professional</label>
    <nameField>
        <label>Medical Professional Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Professionals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Treatment__c.object
<CustomObject>
    <description>What Treatment is the patient interested in.</description>
    <label>Treatment</label>
    <nameField>
        <displayFormat>TR{00000000}</displayFormat>
        <label>Treatment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CareTeamUtil.cls
public with sharing class CareTeamUtil {
   	public static void addMembersToCareTeam( List<Care_Team_Member__c> careTeamMembers ) {
   		Set<ID> treatmentIds = new Set<ID>();
   		for (Care_Team_Member__c member : careTeamMembers) {
   			treatmentIds.add(member.Treatment__c);
   		}
   		Care_Team_Member__c[] members = [SELECT Medical_Professional__c, User__c, External_Contact__c, Treatment__c 
   			FROM Care_Team_Member__c where treatment__c in :treatmentIds];
   		Map<String, String> careTeamMemberMap = new Map<String, String>();
   		for (Care_Team_Member__c member : members) {
   			careTeamMemberMap.put( makeExternalId(member), member.id );
   		}
   		List<Care_Team_Member__c> insertMembers = new List<Care_Team_Member__c>();
   		for (Care_Team_Member__c member : careTeamMembers) {
   			if (!careTeamMemberMap.containsKey(makeExternalId(member))) {
   				insertMembers.add(member);
   				careTeamMemberMap.put( makeExternalId(member), 'NEW');
   			}
   		}
   		if (insertMembers.size()>0) {
	   		insert insertMembers;
   		}
   	}

	public static String makeExternalId( Care_Team_Member__c member ) {
		String key = member.Treatment__c + '+';
		if (member.User__c != null) {
			key += member.User__c;
		} else if (member.Medical_Professional__c != null) {
			key += member.Medical_Professional__c;
		} else if (member.External_Contact__c != null) {
			key += member.External_Contact__c;
		}
		return key;
	}
}