src/objects/Care_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Doctor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Information Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onsite Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Concierge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Treatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Care Team Members</relationshipLabel>
        <relationshipName>Care_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Care_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Care Team Member</label>
    <nameField>
        <label>Care Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Medical_Professional__c.object
<CustomObject>
    <label>Medical Professional</label>
    <nameField>
        <label>Medical Professional Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Professionals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Procedure__c.object
<CustomObject>
    <description>The list of all the procedures in the system.</description>
    <fields>
        <fullName>Doctor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Doctor</label>
        <referenceTo>Medical_Professional__c</referenceTo>
        <relationshipLabel>Procedures</relationshipLabel>
        <relationshipName>Procedures</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Procedure</label>
    <nameField>
        <label>Procedure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Treatment__c.object
<CustomObject>
    <description>What Treatment is the patient interested in.</description>
    <fields>
        <fullName>Procedure__c</fullName>
        <label>Procedure</label>
        <picklist>
            <controllingField>Procedure_Category__c</controllingField>
            <picklistValues>
                <fullName>ACL Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angiogram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angioplasty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anti-Aging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ataxia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autism</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bariatric - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breast Augmentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breast LIft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiac - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiomyopathy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cataract surgery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCSVI Diagnostics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCSVI for MS (venoplasty)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cerebral Palsy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemotherapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Birth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cirrhosis &amp; Hepatitis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cosmetic Combo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cosmetic - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Limb Ischemia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT Scan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Bridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Consult</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Crowns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Dentures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Fillings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Treatment</label>
    <nameField>
        <displayFormat>TR{00000000}</displayFormat>
        <label>Treatment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Treatment_Quote__c.object
<CustomObject>
    <description>Quotes to send to patients.</description>
    <fields>
        <fullName>Treatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Treatment Quotes</relationshipLabel>
        <relationshipName>Treatment_Treatment_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Treatment Quote</label>
    <nameField>
        <displayFormat>IQ{00000000}</displayFormat>
        <label>Interaction Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TreatmentQuoteUtility.cls
public with sharing class TreatmentQuoteUtility {

/* Get Treatment__c, Procedure__r.Doctor__r.Key_Contact__c from quote
key_contact__c = :user.contactid
*/
    public static void afterInsert (List<Treatment_Quote__c> treatmentQuotes){
		addDoctorsToCareTeamIfNeeded( treatmentQuotes );
    }

    public static void afterUpdate (List<Treatment_Quote__c> newQuotes){
		addDoctorsToCareTeamIfNeeded( newQuotes );
    }

	private static void addDoctorsToCareTeamIfNeeded(List<Treatment_Quote__c> treatmentQuotes) {
		loadQuoteRelatedData( treatmentQuotes );
	}
	private static Map<ID, ID> contactToDoctorMap = null;
	private static void loadContactToDoctorMap(Set<ID> contacts) {
system.debug('contacts='+contacts);
		User[] doctors = [select id, ContactId from User where ContactId in :contacts];
system.debug('doctors='+doctors);
		contactToDoctorMap = new Map<ID, ID>();
		for (User doctor : doctors) {
			contactToDoctorMap.put(doctor.ContactId, doctor.id);
		}
	}
	private static void loadQuoteRelatedData( List<Treatment_Quote__c> treatmentQuotes ) {
		Set<ID> treatmentQuoteIds = new Set<ID>();
    	for (Treatment_Quote__c quote : treatmentQuotes) {
    		treatmentQuoteIds.add(quote.id);
    	}
		Map<ID, Treatment_Quote__c> quoteMap = new Map<ID, Treatment_Quote__c>([select 
			Treatment__c, 
			Procedure__r.Doctor__r.Key_Contact__c 
			from Treatment_Quote__c 
			where id in :treatmentQuoteIds]);
		Set<ID> contactIds = new Set<ID>();
		for (Treatment_Quote__c quote : quoteMap.values()) {
			if (quote.Procedure__c != null && quote.Procedure__r.Doctor__c != null && quote.Procedure__r.Doctor__r.Key_Contact__c != null) {
				contactIds.add(quote.Procedure__r.Doctor__r.Key_Contact__c);
			}
		}
		loadContactToDoctorMap(contactIds);
		List<Care_Team_Member__c> insertMembers = new List<Care_Team_Member__c>();
    	for (Treatment_Quote__c quote : treatmentQuotes) {
    		ID treatmentId = quote.Treatment__c;
   			Treatment_Quote__c expandedQuote = quoteMap.get(quote.id);
   system.debug('Looking for contact '+expandedQuote.Procedure__r.Doctor__r.Key_Contact__c);
    		ID doctorId = contactToDoctorMap.get(expandedQuote.Procedure__r.Doctor__r.Key_Contact__c);
    		if (doctorId != null) {
    			insertMembers.add(new Care_Team_Member__c(Treatment__c = treatmentId, User__c = doctorId, Role__c = 'Doctor'));
    		}
    	}
    	CareTeamUtil.addMembersToCareTeam(insertMembers);
	}
	
}