src/objects/Insurance_Network__c.object
<CustomObject>
    <label>Insurance Network</label>
    <nameField>
        <label>Insurance Network Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Networks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Medical_Facility__c.object
<CustomObject>
    <label>Medical Facility</label>
    <nameField>
        <label>Medical Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PRM_Config__c.object
<CustomObject>
    <fields>
        <fullName>Public_Group__c</fullName>
        <description>Enter the name of an existing Public Group. Public Groups are defined under Setup, Administration Setup, Manage Users, Public Groups. This Public Group defines the Facilitator Orgs PCCs. There is a corresponding group for each Medical Facility.</description>
        <label>Public Group</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>PRM Config</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRM Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccessUtil.cls
public with sharing class AccessUtil {
	public static User[] getMedicalFacilityUsers( ID medicalFacilityId ) {
      	Medical_Facility__c medicalFacility = [select Public_Group__c from Medical_Facility__c 
      			where id = :medicalFacilityId limit 1];
      	return [ Select Id, Name, Email from User where id in 
      			(select UserOrGroupId from GroupMember  
                             Where Group.Name = :medicalFacility.Public_Group__c) ];
	}
	public static User[] getFacilitatorOrgUsers() {
		PRM_Config__c prmConfig = [Select Public_Group__c from PRM_Config__c Limit 1];
      	return [ Select Id, Name, Email from User where id in 
      			(select UserOrGroupId from GroupMember  
                             Where Group.Name = :prmConfig.Public_Group__c) ];
	}

	public static User[] getInsuranceNetworkUsers() {
		Insurance_Network__c insNetwork = [Select Public_Group__c from Insurance_Network__c Limit 1];
      	return [ Select Id, Name, Email from User where id in 
      			(select UserOrGroupId from GroupMember  
                             Where Group.Name = :insNetwork.Public_Group__c) ];
	}
	
}