src/objects/Medical_Profile__c.object
<CustomObject>
    <description>The medical profile of the patient</description>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Medical Profiles</relationshipLabel>
        <relationshipName>Medical_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Treatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Medical Profiles</relationshipLabel>
        <relationshipName>Treatment_Medical_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Medical Profile</label>
    <nameField>
        <displayFormat>MQ{0000000000}</displayFormat>
        <label>Medical Profile</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Message__c.object
<CustomObject>
    <description>This object will support internal office messages among users, and office to patient users as well.</description>
    <label>Message</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Patient__c.object
<CustomObject>
    <description>Core object in the PRM data model.</description>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Payment record for the Interaction</description>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Treatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Treatment_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY{00000000}</displayFormat>
        <label>Payment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Travel__c.object
<CustomObject>
    <description>Travel Plans</description>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Travels</relationshipLabel>
        <relationshipName>Travels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Treatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Travels</relationshipLabel>
        <relationshipName>Treatment_Travels</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Travel</label>
    <nameField>
        <label>Travel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Treatment__c.object
<CustomObject>
    <description>What Treatment is the patient interested in.</description>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Treatments</relationshipLabel>
        <relationshipName>Treatments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>(1) Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(2) Interaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(3) Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(4) Post-Op</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Travel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Travel</label>
        <referenceTo>Travel__c</referenceTo>
        <relationshipLabel>Treatments</relationshipLabel>
        <relationshipName>Treatments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Treatment</label>
    <nameField>
        <displayFormat>TR{00000000}</displayFormat>
        <label>Treatment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PatientExtension.cls
/**
* Name        : PatientExtension
* Description : To display Patient and Related data on Patient Tab
* CreatedBy   : Ramadevi Kanchadapu
*/ 
public class PatientExtension {
  public Patient__c patient { get; set; }
  public Treatment__c treatment { get; set; }    
  public Travel__c travel { get; set; }
  public List<Message__c> messages { get; set; }
  public List<Task> tasks { get; set; }  
  public Payment__c payment { get; set; }   
  public Medical_Profile__c medProfile { get; set; }
  public List<SelectOption> taskOptions { get; set; }
  public String selectedTaskOption { get; set; }
  public String firstName { get; set; }
  public String lastName { get; set; }
  public String phaseCount { get; set; }    
  public Boolean inquiryFlag { get; set; }    
  public Boolean interactionFlag { get; set; }    
  public Boolean travelFlag { get; set; }
  public Boolean postopFlag { get; set; }
            
  public PatientExtension(ApexPages.StandardController sc) {
    this.patient = (Patient__c)sc.getRecord();
    this.inquiryFlag = true;
    this.interactionFlag = false;
    this.travelFlag = false;
    this.postopFlag = false;
    this.selectedTaskOption = 'All Open';
      taskOptions = new List<SelectOption>();
      taskOptions.add(new SelectOption('All Open', 'All Open'));
      taskOptions.add(new SelectOption('All Closed', 'All Closed'));
      taskOptions.add(new SelectOption('My Open', 'My Open'));
      taskOptions.add(new SelectOption('My Closed', 'My Closed'));  
    
    try{
	   this.patient = PatientUtil.queryPatientAll(this.patient.Id);
     
     if (patient != null){
      this.firstName = this.patient.Name.split(' ')[0];   
      this.lastName = this.patient.Name.split(' ')[1]; 

      if  (treatment.Phase__c.contains( 'Post-Op' )) {phaseCount = '4';}   
      if  (treatment.Phase__c.contains( 'Inquiry' )) {phaseCount = '1';}  
      if (treatment.Phase__c.contains( 'Interaction' )) {phaseCount = '2';}  
      if  (treatment.Phase__c.contains( 'Travel' )) {phaseCount = '3';}   
                                                        
                                                          
      }          
    }catch(Exception e){
      ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.Info, e.getMessage()));
    }
  }    
  public void displayInquiry(){
    inquiryFlag = true;
    interactionFlag = false;
    travelFlag = false;
    postopFlag = false;
  }    
  public void displayInteraction(){
    inquiryFlag = false;
    interactionFlag = true;
    travelFlag = false;
    postopFlag = false;
  }        
  public void displayTravel(){
    inquiryFlag = false;
    interactionFlag = false;
    travelFlag = true;
    postopFlag = false;
  }      
  public void displayPostOp(){
    inquiryFlag = false;
    interactionFlag = false;
    travelFlag = false;
    postopFlag = true;
  }     
  public void searchTask(){
    Id currentUserId =   UserInfo.getUserId();
    this.tasks = new List<Task>();
    	
    try {
         
      if (selectedTaskOption == 'All Open') {
        for (Task t : this.patient.Tasks) {
          if (t.Status != 'Completed') {  	 
        	  this.tasks.add(t);
          }
        }
      } else if (selectedTaskOption == 'My Open') {
        for (Task t : this.patient.Tasks) {
          if (t.Status !='Completed' && t.Ownerid == currentUserId) {
          	this.tasks.add(t);
          }
        }
      } else if (selectedTaskOption == 'All Closed') {
        for (Task t : this.patient.Tasks) {
        	if (t.Status == 'Completed') {
        		this.tasks.add(t);
        	}
        }
      } else if (selectedTaskOption == 'My Closed') {
        for (Task t : this.patient.Tasks) {
        	if (t.Status !='Completed' && t.Ownerid == currentUserId) {
        		this.tasks.add(t);
        	}
        }
      }                                                                 
    }catch(Exception e){
      ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.Info, e.getMessage()));
    }
  }   
  static testMethod void testPatientExtension(){
    Patient__c pat = new Patient__c();
    pat.name = 'Test';
    insert pat;
        
    Treatment__c t = new Treatment__c();
    t.Patient__c = pat.id;
    insert t;
    Task task = new Task();
    task.subject ='Test';
    task.Status = 'Completed';
    insert task ;
    
    PatientExtension pe = new PatientExtension( new ApexPages.StandardController(pat));
    pe.displayInquiry();    
    pe.displayInteraction();
    pe.displayTravel();
    pe.displayPostOp();
    pe.selectedTaskOption = 'All Closed';
    pe.searchTask();    
  }        
}