src/objects/Medical_Profile_Header__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Medical Profile Headers</relationshipLabel>
        <relationshipName>Survey_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <externalId>true</externalId>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Medical Profile Header</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Profile Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Medical_Profile_Question__c.object
<CustomObject>
    <fields>
        <fullName>Medical_Profile_Header__c</fullName>
        <label>Medical Profile Header</label>
        <referenceTo>Medical_Profile_Header__c</referenceTo>
        <relationshipLabel>Medical Profile Questions</relationshipLabel>
        <relationshipName>Medical_Profile_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Medical Profile Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Profile Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Patient__c.object
<CustomObject>
    <description>Core object in the PRM data model.</description>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Satisfaction_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Survey_ID__c</fullName>
        <externalId>true</externalId>
        <label>Survey ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treatment__c</fullName>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Satisfaction Surveys</relationshipLabel>
        <relationshipName>Satisfaction_Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Satisfaction Survey</label>
    <nameField>
        <label>Survey Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Satisfaction Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Satisfaction_Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Satisfaction_Survey__c</fullName>
        <label>Satisfaction Survey</label>
        <referenceTo>Satisfaction_Survey__c</referenceTo>
        <relationshipLabel>Satisfaction Survey Questions</relationshipLabel>
        <relationshipName>Satisfaction_Survey_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Satisfaction Survey Question</label>
    <nameField>
        <label>Satisfaction Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Satisfaction Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Treatment__c.object
<CustomObject>
    <description>What Treatment is the patient interested in.</description>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Treatments</relationshipLabel>
        <relationshipName>Treatments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Treatment</label>
    <nameField>
        <displayFormat>TR{00000000}</displayFormat>
        <label>Treatment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/surveyPDF_Controller.cls
public with sharing class surveyPDF_Controller {

	public string type {get;set;}
	public Medical_Profile_Header__c medicalProfile {get;set;}
    public list<Medical_Profile_Question__c> medicalProfileQuestions {get;set;} 
    public Satisfaction_Survey__c satisfactionSurvey {get;set;}
    public list<Satisfaction_Survey_Question__c> satisfactionSurveyQuestions {get;set;}
    public string patientName {get;set;}
    public boolean error {get;set;}
    
    public surveyPDF_Controller(){
    	error = false;
    	if (apexpages.currentpage().getparameters().get('type')!=null) {
    		type = apexpages.currentpage().getparameters().get('type');
    	}
    	
    	if (type == 'm' && apexpages.currentpage().getparameters().get('id') != null) {
    		medicalProfile = [select id, name, patient__c, profile_id__c, patient__r.name from Medical_Profile_Header__c where id = :apexpages.currentpage().getparameters().get('id')];
    		medicalProfileQuestions = patientUtil.queryMedicalProfileQuestions(medicalProfile.id);
    	}
    	else if (type=='s' && apexpages.currentpage().getparameters().get('id') != null) {
    		satisfactionSurvey = [select id, name, survey_id__c, treatment__c, treatment__r.patient__r.name from Satisfaction_Survey__c where id = :apexpages.currentpage().getparameters().get('id')];
    		satisfactionSurveyQuestions = treatmentUtility.querySatisfactionSurveyQuestions(satisfactionSurvey.id);
    	}
    	else{
    		error = true;
    		apexpages.addmessage(new ApexPages.Message(ApexPages.Severity.error, 'Could not find a survey of this type with specified id.'));
    	}
    }  
}