src/objects/Medical_Record__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MphRxDate__c</fullName>
        <description>Date assigned by MphRx</description>
        <label>MphRx Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MphRxObjectID__c</fullName>
        <description>The object ID assigned to the record by MphRx</description>
        <label>MphRxObjectID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectType__c</fullName>
        <label>Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Medical Records</relationshipLabel>
        <relationshipName>Medical_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Medical Record</label>
    <nameField>
        <label>Medical Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/mphRxAPI__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Settings needed to connect to MphRx&apos;s web API.</description>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>cert__c</fullName>
        <label>cert</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>MphRX API</label>
</CustomObject>

src/objects/Patient__c.object
<CustomObject>
    <description>Core object in the PRM data model.</description>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MedicalRecordUtility.cls
public with sharing class MedicalRecordUtility {

//  	private String testRecordsList = '{"medicalObjects": {"medicalObjects":[\n{\n"objectId": "VLcbStHf1d9S2X6Eugs0",\n"objectType": "someType",\n"description": "A medical record of some type.",\n"date": "1357685363000"\n},\n{\n"objectId": "tG3oIsLG7jqI4LEW5LR7",\n"objectType": "someOtherType",\n"description":  "A medical record of some other type.",\n"date": "1368359603000"\n}\n,\n{\n"objectId": "Wx4aUPVoF9MlujHxisyr",\n"objectType": "yetAnotherType",\n"description":  "A medical record of yet another type.",\n"date": "1374129681000"\n}\n]\n}\n}';
  public class MphRxCallout 
  {
  	public String getContent(String urlCommand, List<String> urlParameters)
  	{    
  		List<mphRxAPI__c> mphRxSetting = mphRxAPI__c.getAll().values();
  		String result = null;
  		if (! mphRxSetting.isempty())
  		{
		  	String url = mphRxSetting[0].URL__c;
		  	String cert = mphRxSetting[0].cert__c;
		  	String pwd = mphRxSetting[0].Password__c;
		    Http h = new Http();    
		    HttpRequest req = new HttpRequest();
		    String urlParameterString = null;
		    for (String s : urlParameters)
		    {
		    	urlParameterString = urlParameterString + '&' + EncodingUtil.urlEncode(s, 'UTF-8');
		    }
		    url = url + urlCommand + '?cert=' + cert + '&password=' + pwd + urlParameterString;
		    req.setEndpoint(url);
		    req.setMethod('GET');
		    Logger.info(req.toString());
//		    HttpResponse res = h.send(req);
//		    result = res.getBody();
  		}
  		return String.isEmpty(result) ? result : null;   		
  	}
  }
  public static List<Medical_Record__c> deserializeMphRxRecordsList(String JSONinput)
  {
  	Map<String, Object> recordsMap = (Map<String, Object>) JSON.deserializeUntyped(JSONinput);
    Set<String> keys = new Set<String>();
    keys = recordsMap.keySet();
	  for (String s : keys)
	  {
	  	Object o = recordsMap.get(s);
	  	Logger.info(s + ':' + o);
	  }
    Map<String, Object> innerMap = new Map<String, Object>();
    innerMap = (Map<String, Object>)recordsMap.get('medicalObjects');
    keys = innerMap.keySet();
    for (String s : keys)
    {
      Object o = innerMap.get(s);
      Logger.info(s + ':' + o);
    }    
    List<Object> objectList = new List<Object>();
    objectList = (List<Object>) innerMap.get('medicalObjects');
    List<Medical_Record__c> medicalRecords = new List<Medical_Record__c>(); 
    for (Object o : objectList)
    {
    	Map<String,Object> objectMap = new Map<String,Object>();
    	objectMap = (Map<String, Object>)o;
    	Medical_Record__c mr = new Medical_Record__c();
    	mr.MphRxObjectID__c = (String)objectMap.get('objectId');
    	String dateString = (String)objectMap.get('date');
    	mr.MphRxDate__c = DateTime.newInstance(Long.valueOf(dateString));
    	mr.ObjectType__c = (String)objectMap.get('objectType');
    	mr.Description__c = (String)objectMap.get('description');
    	medicalRecords.add(mr);
      Logger.info('Object: ' + mr);
    }
  	return medicalRecords;
  }
  public static Integer createMphRxPatientRecord(Patient__c patient)
  {
  	Integer mphRxPatientID;
  	return mphRxPatientID;
  }
}