src/objects/Medical_Facility__c.object
<CustomObject>
    <label>Medical Facility</label>
    <nameField>
        <label>Medical Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Medical_Professional__c.object
<CustomObject>
    <label>Medical Professional</label>
    <nameField>
        <label>Medical Professional Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Professionals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Patient__c.object
<CustomObject>
    <description>Core object in the PRM data model.</description>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Procedure__c.object
<CustomObject>
    <description>The list of all the procedures in the system.</description>
    <fields>
        <fullName>Doctor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Doctor</label>
        <referenceTo>Medical_Professional__c</referenceTo>
        <relationshipLabel>Procedures</relationshipLabel>
        <relationshipName>Procedures</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>What Hospital, facility provides this Procedure.</description>
        <label>Facility</label>
        <referenceTo>Medical_Facility__c</referenceTo>
        <relationshipLabel>Procedures</relationshipLabel>
        <relationshipName>Procedures</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Procedure</label>
    <nameField>
        <label>Procedure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Treatment__c.object
<CustomObject>
    <description>What Treatment is the patient interested in.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Treatments</relationshipLabel>
        <relationshipName>Treatments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Procedure__c</fullName>
        <label>Procedure</label>
        <picklist>
            <controllingField>Procedure_Category__c</controllingField>
            <picklistValues>
                <fullName>ACL Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angiogram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angioplasty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anti-Aging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ataxia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autism</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bariatric - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breast Augmentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breast LIft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiac - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiomyopathy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cataract surgery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCSVI Diagnostics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCSVI for MS (venoplasty)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cerebral Palsy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemotherapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Birth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cirrhosis &amp; Hepatitis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cosmetic Combo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cosmetic - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Limb Ischemia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT Scan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Bridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Consult</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Crowns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Dentures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Fillings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Treatment</label>
    <nameField>
        <displayFormat>TR{00000000}</displayFormat>
        <label>Treatment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Treatment_Quote__c.object
<CustomObject>
    <description>Quotes to send to patients.</description>
    <fields>
        <fullName>Arrival_Date__c</fullName>
        <label>Arrival Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ground_Transportation_Included__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ground Transportation Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hotel_Nights_Included__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hotel Nights Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hotel_Nights_Needed__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Hotel Nights Needed</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Hospital_Nights__c</fullName>
        <label>Number of Hospital Nights</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Treatment Quotes</relationshipLabel>
        <relationshipName>Treatment_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Treatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Treatment Quotes</relationshipLabel>
        <relationshipName>Treatment_Treatment_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Treatment Quote</label>
    <nameField>
        <displayFormat>IQ{00000000}</displayFormat>
        <label>Interaction Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuoteUtility.cls
public with sharing class QuoteUtility {
    public static Treatment_Quote__c queryQuoteForQuoteDoc(Id pQuoteId) { 
      if(pQuoteId == null) {          
        return null;
      } else {           
        return [Select id, 
                        Total_Price__c,
                        Treatment__r.Name,
                        Treatment__r.Amount__c,                      
                        Treatment__r.Procedure__c, 
                        Treatment__r.Patient__r.Name,
                        Treatment__r.Patient__r.Owner.Name,                        
                        Arrival_Date__c,
                        Departure_Date__c,
                        Number_of_Hospital_Nights__c,
                        Hotel_Nights_Included__c,
                        Hotel_Nights_Needed__c,
                        Ground_Transportation_Included__c,
                        Procedure__r.Facility__r.Name,
                        Procedure__r.Doctor__r.Name,
                        Procedure__r.Price__c
                    from Treatment_Quote__c 
                    where id = :pQuoteId];               
      }  
   }
}