src/objects/Message__c.object
<CustomObject>
    <description>This object will support internal office messages among users, and office to patient users as well.</description>
    <fields>
        <fullName>Body_Rich_Text__c</fullName>
        <label>Body</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsRead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Message_Header__c</fullName>
        <description>messages under the header</description>
        <label>Message Header</label>
        <referenceTo>Message_Header__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Truncated_Body__c</fullName>
        <description>This field will be filled out by apex code and is used to display in the users message inbox</description>
        <label>Body</label>
        <type>TextArea</type>
    </fields>
    <label>Message</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Message_Header__c.object
<CustomObject>
    <description>conjunction object that links users to messages</description>
    <label>Message Header</label>
    <nameField>
        <displayFormat>MHN-{00000000}</displayFormat>
        <label>Message Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Message Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Message.cls
/*
 * this class will support the message object and help display, retrieve,
 * and save data to the message data model.
 * author mfullmore
*/

public class Message {
  

  public static List<Message.MsgResult> getUserMessages(User pUser) {
    Message_Header__c msgHeader;
    List<Message.MsgResult> results;

    if (pUser == null) {
      
      return null; 
    } else {
      msgHeader = [select Id,
                          Name,
                          Users__c,
                          (select Id,
                                  Body_Rich_Text__c,
                                  Truncated_Body__c,
                                  Priority__c,
                                  IsRead__c
                          from Messages__r)
                   from Message_Header__c];
                   //where Users__c like '%' : pUser.Id];

        
    }
    return results;
  }

  public class MsgResult {
    public Message_Header__c msgHeader { get; private set; }
    public List<Message__c> msgs { get; private set; }
    public List<User> users { get; private set; }

    public MsgResult(Message_Header__c pMessageHeader,
      List<Message__c> pMessages,
      List<User> pUsers) {
    
      this.msgHeader = pMessageHeader;
      this.msgs = pMessages;
      this.users = pUsers;
    }
  }
}