src/objects/Message__c.object
<CustomObject>
    <description>This object will support internal office messages among users, and office to patient users as well.</description>
    <fields>
        <fullName>Body_Rich_Text__c</fullName>
        <label>Body</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Message_Header__c</fullName>
        <description>messages under the header</description>
        <label>Message Header</label>
        <referenceTo>Message_Header__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Message</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Message_Header__c.object
<CustomObject>
    <description>conjunction object that links users to messages</description>
    <label>Message Header</label>
    <nameField>
        <displayFormat>MHN-{00000000}</displayFormat>
        <label>Message Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Message Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Message_Test.cls
/*
Obsolete - replaced by MK Partners Messaging
*/



public class Message_Test {
/*
  static testMethod void testMessage() {
    Profile pro = [select Id from Profile where Name = 'Standard User'];
    User testUser;
    List<Message.MsgResult> results;
    
    List<User> testUsers = new List<User>();
    
    for (Integer i = 0; i < 3; i++) {
       testUser = new User(FirstName = 'Test',
         LastName = 'User' + String.valueOf(i),
         UserName = 'test' + String.valueOf(Math.random()) + '@htt.com',
         Email = 'test@test.com',
         ProfileId = pro.Id,
         LanguageLocaleKey = 'en_US',
         LocaleSidKey = 'en_US',
         TimeZoneSidKey = 'America/Los_Angeles',
         EmailEncodingKey = 'ISO-8859-1',
         Alias = 'test');
    
      testUsers.add(testUser);
    }
    
    insert testUsers;
    
    for (Integer i = 0; i < 2; i++) {
      System.assert(
        Message.createMessage(
          new Message__c(
            Body_Rich_Text__c = 'Test body' + i,
            Priority__c = 'Medium'
          ),
          testUsers
        )
      );
    }
    
    results = Message.getUserMessages(testUsers[0]);
    System.assert(results[0].msgs[0].Body_Rich_Text__c.contains('Test body'));
      
    Message.addToMessage(
      results[0].msgHeader,
      new Message__c(Body_Rich_Text__c = 'Test Msg')
    );
    
    System.assertEquals(
      2,
      [select count() 
       from Message__c 
       where Message_Header__c = :results[0].msgHeader.Id]  
    );
    
    Message.addToMessage(
      results[0].msgHeader.Id,
      new Message__c(Body_Rich_Text__c = 'Test Msg2')
    );    
    
    System.assertEquals(
      3,
      [select count() 
       from Message__c 
       where Message_Header__c = :results[0].msgHeader.Id]  
    );  
  }*/
}