src/objects/Patient__c.object
<CustomObject>
    <description>Core object in the PRM data model.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Travel__c.object
<CustomObject>
    <description>Travel Plans</description>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Travels</relationshipLabel>
        <relationshipName>Travels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Treatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Travels</relationshipLabel>
        <relationshipName>Treatment_Travels</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Travel</label>
    <nameField>
        <label>Travel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Treatment__c.object
<CustomObject>
    <description>What Treatment is the patient interested in.</description>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Treatments</relationshipLabel>
        <relationshipName>Treatments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>(1) Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(2) Interaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(3) Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(4) Post-Op</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <controllingField>Phase__c</controllingField>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Responding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Established</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested but not Responding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested but Hold for Later</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment Approval Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment Approved/Quoting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consult</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Itinerary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship Terminated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Travel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Travel</label>
        <referenceTo>Travel__c</referenceTo>
        <relationshipLabel>Treatments</relationshipLabel>
        <relationshipName>Treatments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Treatment</label>
    <nameField>
        <displayFormat>TR{00000000}</displayFormat>
        <label>Treatment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Treatment_Quote__c.object
<CustomObject>
    <description>Quotes to send to patients.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Treatment Quotes</relationshipLabel>
        <relationshipName>Treatment_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Treatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Treatment Quotes</relationshipLabel>
        <relationshipName>Treatment_Treatment_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Treatment Quote</label>
    <nameField>
        <displayFormat>IQ{00000000}</displayFormat>
        <label>Interaction Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RequestQuoteController.cls
public with sharing class RequestQuoteController 
{
	
  public Patient__c patient {get; set; }
  public Treatment__c treatment {get; set; }
  public Travel__c travel { get; set; }    
  public Treatment_Quote__c treatmentQuote { get; set; }
  
  public String reference_number { get; set; }
  public String authorized_by_insurance { get; set; }
  public String guardian_info { get; set; }
  public String guardian_additional { get; set; }
  public String caller_referral_comments { get; set; }
  public String preferred_facility { get; set; }
  public String medical_diagnosis { get; set; }
  public String symptom_summary { get; set; } 
  public String time_frame { get; set; } 
  public String preferred_appointment { get; set; } 
  public String concierge_needed { get; set; } 
  private Map<String, String> URLParams { get; set; } 
  public RequestQuoteController()
  {
  	treatment = new Treatment__c();
  	patient = new Patient__c();
  	travel = new  Travel__c();
  	URLparams = System.currentPagereference().getParameters();
    if (URLparams.containsKey('nextLead'))
    {
      ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.CONFIRM, 'Lead submitted. Submit next lead below.'));
    }    	  	
  }
  public PageReference submitLead()
  {
    //Check to see if patient already exists
    List<Patient__c> patients = [Select Id FROM Patient__c WHERE Email__c = : patient.Email__c];
    if (patients.size() > 0)
    {
      patient = patients[0];
    }
    treatment.Phase__c = PickListDefines.Phase.Inquiry;
    treatment.Stage__c = PickListDefines.Stage.Initial;
    if (URLparams.containsKey('enteredBy'))
    {    
      treatment.Lead_Entry__c = URLparams.get('enteredBy');
    }
    INSERT travel;    
    if (patient.Id == null) { INSERT patient; }
    else { UPDATE patient; }
    treatment.Travel__c = travel.id;
    treatment.Patient__c = patient.id;    
    INSERT treatment; 
    Note resultsNote = new Note(); 
    String noteBody = '';   
    if (! String.isBlank(reference_number) )
    {
    	noteBody += 'Reference number: ' + reference_number + ' \r\n';
    }
    if (! String.isBlank(authorized_by_insurance) )
    {
      noteBody += 'Authorized by insurance: ' + authorized_by_insurance + ' \r\n';
    } 
    if (! String.isBlank(guardian_info) )
    {
      noteBody += 'Guardian info: ' + guardian_info + ' \r\n';
    }
    if (! String.isBlank(guardian_additional) )
    {
      noteBody += 'Additional guardian info: ' + guardian_additional + ' \r\n';
    } 
    if (! String.isBlank(caller_referral_comments) )
    {
      noteBody += 'Comments about caller/referral: ' + caller_referral_comments + ' \r\n';
    } 
    if (! String.isBlank(preferred_facility) )
    {
      noteBody += 'Preferred facility type and location: ' + preferred_facility + ' \r\n';
    } 
    if (! String.isBlank(medical_diagnosis) )
    {
      noteBody += 'Medical diagnosis: ' + medical_diagnosis + ' \r\n';
    } 
    if (! String.isBlank(symptom_summary) )
    {
      noteBody += 'Current symptoms and issues: ' + symptom_summary + ' \r\n';
    } 
    if (! String.isBlank(time_frame) )
    {
      noteBody += 'Desired treatment time frame: ' + time_frame + ' \r\n';
    } 
    if (! String.isBlank(preferred_appointment) )
    {
      noteBody += 'Preferred treatment/procedure appointment: ' + preferred_appointment + ' \r\n';
    } 
    if (! String.isBlank(concierge_needed) )
    {
      noteBody += 'Travel concierge services required? ' + concierge_needed + ' \r\n';
    }                                  
    if (! String.isBlank(noteBody) )
    {
    	resultsNote.Title = 'Lead Entry Responses';
      resultsNote.ParentId = patient.id;
      resultsNote.Body = noteBody;
      INSERT resultsNote;
    }
    PageReference nextEntry = new PageReference(ApexPages.currentPage().getUrl());
    nextEntry.setRedirect(true);
    nextEntry.getParameters().put('nextLead', '1');    
    return nextEntry;    

  }   
  public PageReference requestQuote()
  {
  	//Check to see if patient already exists
  	List<Patient__c> patients = [Select Id FROM Patient__c WHERE Email__c = : patient.Email__c];
  	if (patients.size() > 0)
  	{
  		patient = patients[0];
  	}
  	treatment.Phase__c = PickListDefines.Phase.Inquiry;
  	treatment.Stage__c = PickListDefines.Stage.Initial;
  	INSERT travel;  	
  	if (patient.Id == null) { INSERT patient; }
  	else { UPDATE patient; }
  	treatment.Travel__c = travel.id;
  	treatment.Patient__c = patient.id;
  	INSERT treatment;
  	PageReference thankYouPage = Page.Request_Quote_Thank_You;  
    return thankYouPage;
  }
 
}