src/objects/Patient__c.object
<CustomObject>
    <description>Core object in the PRM data model.</description>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Treatment__c.object
<CustomObject>
    <description>What Treatment is the patient interested in.</description>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Treatments</relationshipLabel>
        <relationshipName>Treatments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Treatment</label>
    <nameField>
        <displayFormat>TR{00000000}</displayFormat>
        <label>Treatment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NotificationController.cls
public with sharing class NotificationController {
  public Treatment__c treatment {get; set; }
  public String treatmentId;
  public void setTreatmentId(String i){ treatmentId = i; }
  public String getTreatmentId() { return treatmentId; }
  public String treatmentURL {
  	get {
  		if (treatment != null) { return '/Patient?id=' + treatment.Patient__c + '&tid=' + treatment.Id; }
  		else return '';
  	}
  	set;
  }
  public void NotificationController()
  {
  	treatment = new Treatment__c();
  }
  public void loadTreatmentInfo()
  {
  	Logger.info('TreatmentId: ' + treatmentId);
  	if (treatmentId != null)
  	{
  	   List<Treatment__c> treatments = [Select Name, Id, Patient__r.Name, Patient__c from Treatment__c Where Id = : treatmentId];
  	   if (treatments.size() > 0) { treatment = treatments[0]; }
  	}
  } 
}