src/objects/Patient__c.object
<CustomObject>
    <description>Core object in the PRM data model.</description>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Travel__c.object
<CustomObject>
    <description>Travel Plans</description>
    <label>Travel</label>
    <nameField>
        <label>Travel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Treatment__c.object
<CustomObject>
    <description>What Treatment is the patient interested in.</description>
    <fields>
        <fullName>Arrival_Time__c</fullName>
        <formula>Travel__r.Travel_Start__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Treatments</relationshipLabel>
        <relationshipName>Treatments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Procedure_Date__c</fullName>
        <label>Procedure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Procedure__c</fullName>
        <label>Procedure</label>
        <picklist>
            <controllingField>Procedure_Category__c</controllingField>
            <picklistValues>
                <fullName>ACL Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angiogram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angioplasty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anti-Aging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ataxia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autism</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bariatric - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breast Augmentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breast LIft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiac - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiomyopathy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cataract surgery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCSVI Diagnostics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCSVI for MS (venoplasty)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cerebral Palsy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemotherapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Birth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cirrhosis &amp; Hepatitis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cosmetic Combo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cosmetic - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Limb Ischemia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT Scan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Bridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Consult</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Crowns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Dentures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Fillings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Travel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Travel</label>
        <referenceTo>Travel__c</referenceTo>
        <relationshipLabel>Treatments</relationshipLabel>
        <relationshipName>Treatments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Treatment</label>
    <nameField>
        <displayFormat>TR{00000000}</displayFormat>
        <label>Treatment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Treatment_Quote__c.object
<CustomObject>
    <description>Quotes to send to patients.</description>
    <fields>
        <fullName>Arrival_Date__c</fullName>
        <label>Arrival Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hotel_Nights_Included__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hotel Nights Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Treatment Quotes</relationshipLabel>
        <relationshipName>Treatment_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Procedure_Date__c</fullName>
        <label>Procedure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Treatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Treatment Quotes</relationshipLabel>
        <relationshipName>Treatment_Treatment_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Treatment Quote</label>
    <nameField>
        <displayFormat>IQ{00000000}</displayFormat>
        <label>Interaction Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ArrivalsReportController.cls
public with sharing class ArrivalsReportController {
  public List<Treatment_Quote__c> treatmentQuoteList {get; set; }
  public List<Id> facilityList {get; set; }
  public Date arrivalFilterDate {get; set; }
  
  public ArrivalsReportController()
  {
  	facilityList = new List<Id>();
    treatmentQuoteList = [Select Treatment__r.Patient__r.Name, Treatment__r.Patient__r.Phone__c, Treatment__r.Arrival_Time__c, Treatment__r.Travel__r.Arrival_Airline__r.Name,  
                            Treatment__r.Travel__r.Arrival_Flight_No__c, Treatment__r.Travel__r.Wheel_Chair_Bound__c, Treatment__r.Procedure_Date__c, 
                            Treatment__r.Travel__r.Companion__c, Hotel_Nights_Included__c 
                           From Treatment_Quote__c
                           Where Procedure__r.Facility__c in : facilityList
                              And Arrival_Date__c <= : arrivalFilterDate 
                              And Arrival_Date__c >= TODAY ];
  }
}