src/objects/Private_Message__c.object
<CustomObject>
    <fields>
        <fullName>Recipient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipient</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Private_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Private Message</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Message Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Private Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PrivateMessageUtil.cls
public without sharing class PrivateMessageUtil {

	public static void addSharing( Private_Message__c msg) {
		addSharing( new List<Private_Message__c>{msg});
	}
	public static void addSharing( List<Private_Message__c> msgList) {
		Map<ID, List<ID>> addSharingMap = new Map<ID, List<ID>>();
		for (Private_Message__c msg : msgList) {
			AccessUtility.addSharingToMap( addSharingMap, msg.id, msg.Recipient__c);
		}
		AccessUtility.addSharing( addSharingMap, 'Private_Message__Share' );
	}
	
}