src/objects/PRM_Config__c.object
<CustomObject>
    <fields>
        <fullName>Public_Group__c</fullName>
        <description>Enter the name of an existing Public Group. Public Groups are defined under Setup, Administration Setup, Manage Users, Public Groups. This Public Group defines the Facilitator Orgs PCCs. There is a corresponding group for each Medical Facility.</description>
        <label>Public Group</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>PRM Config</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRM Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PRMConfigUtil.cls
public with sharing class PRMConfigUtil {
    public static void before( List<PRM_Config__c> prmConfigs ) {
        Map<String, Group> groupMap = new Map<String, Group>();
        Group[] groups = [select id, Name from Group];
        for (Group grp : groups) {
            groupMap.put(grp.Name, grp);
        }
        for (PRM_Config__c config : prmConfigs) {
            if (!groupMap.containsKey(config.Public_Group__c)) {
                config.addError('Please enter a valid Public Group name.');
            }
        }
    }
}