src/objects/Server_Log__c.object
<CustomObject>
    <description>Log of errors returned by third-party services.</description>
    <fields>
        <fullName>Error_text__c</fullName>
        <description>Error text returned by the service</description>
        <label>Error text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <description>Name of the service that generated the error.</description>
        <label>Service</label>
        <picklist>
            <picklistValues>
                <fullName>EchoSign</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Server Log</label>
    <nameField>
        <label>Server Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Server Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ServerLogUtility.cls
public with sharing class ServerLogUtility {
  public Server_Log__c serverLog { get; set; }
  public ServerLogUtility (String service, String errorMessage)
  {
  	this.serverLog = new Server_Log__c();
  	this.serverLog.Service__c = service;
  	this.serverLog.Error_text__c = errorMessage;
  }
  public static void updateServerLog (String service, String errorMessage)
  {
  	ServerLogUtility sl = new serverLogUtility(service, errorMessage);
  	insert sl.serverLog;
  }
}