src/objects/Travel__c.object
<CustomObject>
    <description>Travel Plans</description>
    <fields>
        <fullName>Arrived__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Arrived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Treatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Travels</relationshipLabel>
        <relationshipName>Treatment_Travels</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Travel</label>
    <nameField>
        <label>Travel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Treatment__c.object
<CustomObject>
    <description>What Treatment is the patient interested in.</description>
    <fields>
        <fullName>Final_Departure_Date__c</fullName>
        <formula>Travel__r.Travel_End__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Final Departure Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>(1) Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(2) Interaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(3) Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(4) Post-Op</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <controllingField>Phase__c</controllingField>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Responding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Established</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested but not Responding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested but Hold for Later</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment Approval Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment Approved/Quoting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consult</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Itinerary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship Terminated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Stage__c</fullName>
        <label>Sub-Stage</label>
        <picklist>
            <controllingField>Stage__c</controllingField>
            <picklistValues>
                <fullName>Response 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Could Not Recontact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient Providing Medical Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Information Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment Approval Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consult Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consult Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consult Further Booking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consult No Further Booking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show or Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trip Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment Itinerary Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reschedule Trip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trip Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Payment Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Start Follow up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Travel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Travel</label>
        <referenceTo>Travel__c</referenceTo>
        <relationshipLabel>Treatments</relationshipLabel>
        <relationshipName>Treatments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Treatment</label>
    <nameField>
        <displayFormat>TR{00000000}</displayFormat>
        <label>Treatment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TravelUtility.cls
/**
* TravelUtility.cls
* Description : Utility methods for Travel__c trigger
* @author M. Wicherski, MK Partners 2012
*/ 

public with sharing class TravelUtility {
	
	/**
	 * Before Insert Actions
	 * @param Trigger.new list<Travel__c> newlist
	 */
	public static void beforeInsert (list<Travel__c> newlist) {
		
	}
	
	/**
	 * Before Update Actions
	 * @param Trigger.new list<Travel__c> newlist
	 * @param Trigger.oldmap map<id,Travel__c> oldmap
	 */
	public static void beforeUpdate (list<Travel__c> newlist, map<id,Travel__c> oldmap) {
		
	}
	
	/**
	 * After Insert Actions
	 * @param Trigger.new list<Travel__c> newlist
	 */
	public static void afterInsert (list<Travel__c> newlist) {
		updateTreatmentLastDepartureDate(newlist);
	}
	
	/**
	 * After Update Actions
	 * @param Trigger.new list<Travel__c> newlist
	 * @param Trigger.oldmap map<id,Travel__c> oldmap
	 */
	public static void afterUpdate (list<Travel__c> newlist, map<id,Travel__c> oldmap) {
		list<Travel__c> updatedDepartures = new list<Travel__c>();
		list<Travel__c> arrivals = new list<Travel__c>();
		for (integer i=0; i<newlist.size(); i++) {
			if (newlist[i].departure_date__c != null && newlist[i].departure_date__c != oldmap.get(newlist[i].id).departure_date__c) {
				updatedDepartures.add(newlist[i]);
			}	
			else if (newlist[i].arrived__c == true && oldmap.get(newlist[i].id).arrived__c == false) {
				arrivals.add(newlist[i]);
			}
		}
		
		if (updatedDepartures.size() > 0) {
			updateTreatmentLastDepartureDate(updatedDepartures);
		}	
		if (arrivals.size() > 0) {
			updateTreatmentAtProvider(arrivals);
		}
	}
	
	/**
	 * Updates the associated treatment with the last departure date from travel
	 * @param list<Travel__c> newlist
	 */
	public static void updateTreatmentLastDepartureDate(list<Travel__c> newlist){
/*		map<id,list<Travel__c>> treatmentTravelsMap = new map<id,list<Travel__c>>();
		list<Travel__c> templist = new list<Travel__c>();
		for (integer i=0; i<newlist.size(); i++) {
			if (treatmentTravelsMap.containsKey(newlist[i].treatment__c)) {
				templist = treatmentTravelsMap.get(newlist[i].treatment__c);
				templist.add(newlist[i]);
				treatmentTravelsMap.put(newlist[i].treatment__c, templist);
			}
			else {
				templist = new list<Travel__c>();
				templist.add(newlist[i]);
				treatmentTravelsMap.put(newlist[i].treatment__c, templist);
			}
		}
		
		map<id,Treatment__c> treatmentMap = populateTreatmentMap(treatmentTravelsMap.keySet());
		for (String s : treatmentTravelsMap.keySet()) {
			list<Travel__c> travelList = treatmentTravelsMap.get(s);
			for (Travel__c t : travelList) {
				if (treatmentMap.get(s).final_departure_Date__c == null || t.departure_date__c > treatmentMap.get(s).final_departure_Date__c) {
					Treatment__c treat = treatmentMap.get(s);
					treat.Final_Departure_Date__c = t.departure_date__c;
					treatmentMap.put(s, treat);	
				}
			}
		}
		
		update treatmentMap.values();*/	
	}
	
	/**
	 * Updates treatment when travel is 'Arrived'
	 * @param list<Travel__c> arrivals
	 */
	public static void updateTreatmentAtProvider (list<Travel__c> arrivals) {
/*FIXME		set<id> arrivalsTreatments = new set<id>();
		for (Travel__c t : arrivals) {
			arrivalsTreatments.add(t.treatment__c);
		}
		
		list<Treatment__c> treatments = populateTreatmentMap(arrivalsTreatments).values(); 
		for (Treatment__c t : treatments) {
			t.Phase__c = '(3) Travel';
			t.stage__c = 'At Provider';
			t.Sub_Stage__c = 'Treatment In Progress';
		}
		
		update treatments;*/
	}
	
	/**
	 * Utility Method for retrieving a map of Treatment__c by id
	 * @param set<id> Treatments
	 * @return map<id,Treatment__c> for passed in set of treatment ids
	 */
	private static map<id, Treatment__c> populateTreatmentMap (set<id> treatments) {
		if (treatments != null && treatments.size() > 0) {
			return new map<id, Treatment__c>([	select id, 
											final_departure_Date__c,
											stage__c,
											phase__c,
											Sub_Stage__c 
											from Treatment__c 
											where id IN :treatments]);
		}
		else return null;
	}
}